name: bhc_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  curved_navigation_bar: ^1.0.6
  dio: ^5.4.3+1
  equatable: ^2.0.5
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.0
  fluttertoast: ^8.2.6
  font_awesome_flutter: ^10.7.0
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  loader_overlay: ^4.0.0
  searchfield: ^1.0.5
  settings_ui: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

flutter_native_splash:
  android: true
  ios: true
  web: false
  image: assets/splash.png
  color: "#FFFFFF"
  android_12:
    image: assets/splash.png
    color: "#FFFFFF"